/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_sign_in_ (void);
GtkWidget* create_gestion_reservation (void);
GtkWidget* create_gestion_compte (void);
GtkWidget* create_gestion_des_agents_ (void);
GtkWidget* create_gestion_de_service_ (void);
GtkWidget* create_point_de_vue_client_ (void);
GtkWidget* create_point_de_vue_agent (void);
GtkWidget* create_gestion_des_avis___reclamations_ (void);
GtkWidget* create_window1 (void);
GtkWidget* create_gestion_parking_ (void);
